# Use appropriate Rust edition
edition = "2021"
version = "Two"

# Wrap comments after max length of 85 characters
comment_width = 85
wrap_comments = true

# Prevent Windows-style carriage returns
newline_style = "Unix"

# The "Default" setting has a heuristic which splits lines too aggresively.
use_small_heuristics = "Max"
max_width = 88

# Consistent ordering of source code
imports_granularity = "Module"
group_imports = "StdExternalCrate"
